export const en = {
  login: "Login",
  login_title: "Login to Vigorhub",
  username: "Email",
  password: "Password",
  forgot_password: "Forgot password?",
  register_here: "Register",
  bad_credentials: "Bad credentials",
  email_cannot_be_blank: "Email cannot be blank.",
  email_must_be_valid: "Email address must be valid.",
  password_must_be_greather_than_8:
    "Password must be greather than 8 characters.",
  you_have_no_clients: "You have no clients.",
  why_dont_you_invite_clients: "Why don't you invite some?",
  send_invitation: "Send invitation",
  plans: "Plans",
  home: "Home",
  clients: "Clients",
  notifications: "Notifications",
  first_name: "First Name",
  last_name: "Last Name",
  invite_client: "Send invitation",
  email: "Email",
  invite_client_via_email: "Invite client via email",
  client_created_successfully: "Client created successfully.",
  your_client_has_been_added_share_credentials:
    "Your client has been added to your account, share credentials with him so that he can login!",
  client_username: "Client username",
  temp_password: "Temporary password",
  create_client_profile:"Create client profile"
};

export const srb = {
  login: "Uloguj se",
  login_title: "Uloguj se na Vigorhub",
  username: "E-mail",
  password: "Lozinka",
  forgot_password: "Zaboravljena lozinka?",
  register_here: "Registruj se",
  bad_credentials: "Pogresna lozinka",
  email_cannot_be_blank: "Email ne moze da bude prazan",
  email_must_be_valid: "Email mora biti validan",
  password_must_be_greather_than_8: "Lozinka mora biti duza od 8 karaktera.",
  you_have_no_clients: "Jos uvek nemas klijente.",
  why_dont_you_invite_clients: "Zasto ih be bih pozvao?",
  send_invitation: "Posalji pozivnicu",
  plans: "Planovi",
  home: "Pocetna",
  clients: "Klijenti",
  notifications: "Notifikacije",
  first_name: "Ime",
  last_name: "Prezime",
  invite_client: "Posalji poziv",
  email: "E-mail",
  invite_client_via_email: "Pozovi klijenta putem e-maila",
  client_created_successfully: "Klijent uspesno kreiran.",
  your_client_has_been_added_share_credentials:
    "Podelite kredencijale sa klijentom, kako bi mogao da se uloguje u aplikaciju.",
  client_username: "Korisnicko ime",
  temp_password: "Privremena lozinka",
  create_client_profile: "Napravi klijentov profil"
};
