export const AUTHENTICATE = "authenticate"
export const BEGIN_AUTHENTICATION = "beginAuthentication"
export const AUTHENTICATION_SUCCESSFULL = "authenticationSuccessfull"
export const AUTHENTICATION_FAILED = "authenticationFailed"
export const AUTH_VERIFY_SUCCESS = "authVerifySuccess"
export const AUTH_VERIFY_FAILED = "authVerifyFailed"
export const LOGOUT = "logout"